package com.singorenko.revoluttest.util

class Constants {
    companion object{
//        const val ratesQuantity = 32

       const val audShortName = "AUD"
        const val bgnShortName = "BGN"
        const val brlShortName = "BRL"
        const val cadShortName = "CAD"
        const val chfShortName = "CHF"
        const val cnyShortName = "CNY"
        const val czkShortName = "CZK"
        const val dkkShortName = "DKK"
        const val eurShortName = "EUR"
        const val gbpShortName = "GBP"
        const val hkdShortName = "HKD"
        const val hrkShortName = "HRK"
        const val hufShortName = "HUF"
        const val idrShortName = "IDR"
        const val ilsShortName = "ILS"
        const val inrShortName = "INR"
        const val iskShortName = "ISK"
        const val jpyShortName = "JPY"
        const val krwShortName = "KRW"
        const val mxnShortName = "MXN"
        const val myrShortName = "MYR"
        const val nokShortName = "NOK"
        const val nzdShortName = "NZD"
        const val phpShortName = "PHP"
        const val plnShortName = "PLN"
        const val ronShortName = "RON"
        const val rubShortName = "RUB"
        const val sekShortName = "SEK"
        const val sgdShortName = "SGD"
        const val thbShortName = "THB"
        const val tryShortName = "TRY"
        const val usdShortName = "USD"
        const val zarShortName = "ZAR"

        const val audLongName = "Australian Dollar"
        const val bgnLongName = "BGN"
        const val brlLongName = "BRL"
        const val cadLongName = "CAD"
        const val chfLongName = "CHF"
        const val cnyLongName = "CNY"
        const val czkLongName = "CZK"
        const val dkkLongName = "DKK"
        const val eurLongName = "EUR"
        const val gbpLongName = "British Pound"
        const val hkdLongName = "HKD"
        const val hrkLongName = "HRK"
        const val hufLongName = "HUF"
        const val idrLongName = "IDR"
        const val ilsLongName = "ILS"
        const val inrLongName = "INR"
        const val iskLongName = "ISK"
        const val jpyLongName = "JPY"
        const val krwLongName = "KRW"
        const val mxnLongName = "MXN"
        const val myrLongName = "MYR"
        const val nokLongName = "NOK"
        const val nzdLongName = "NZD"
        const val phpLongName = "PHP"
        const val plnLongName = "PLN"
        const val ronLongName = "RON"
        const val rubLongName = "RUB"
        const val sekLongName = "SEK"
        const val sgdLongName = "SGD"
        const val thbLongName = "THB"
        const val tryLongName = "TRY"
        const val usdLongName = "USD"
        const val zarLongName = "ZAR"
    }
}

