package com.singorenko.revoluttest.util

class Constants {
    companion object{

        const val PERIOD_UPDATE_FROM_SERVER: Long = 1
//        const val ratesQuantity = 32

        const val audShortName = "AUD"
        const val bgnShortName = "BGN"
        const val brlShortName = "BRL"
        const val cadShortName = "CAD"
        const val chfShortName = "CHF"
        const val cnyShortName = "CNY"
        const val czkShortName = "CZK"
        const val dkkShortName = "DKK"
        const val eurShortName = "EUR"
        const val gbpShortName = "GBP"
        const val hkdShortName = "HKD"
        const val hrkShortName = "HRK"
        const val hufShortName = "HUF"
        const val idrShortName = "IDR"
        const val ilsShortName = "ILS"
        const val inrShortName = "INR"
        const val iskShortName = "ISK"
        const val jpyShortName = "JPY"
        const val krwShortName = "KRW"
        const val mxnShortName = "MXN"
        const val myrShortName = "MYR"
        const val nokShortName = "NOK"
        const val nzdShortName = "NZD"
        const val phpShortName = "PHP"
        const val plnShortName = "PLN"
        const val ronShortName = "RON"
        const val rubShortName = "RUB"
        const val sekShortName = "SEK"
        const val sgdShortName = "SGD"
        const val thbShortName = "THB"
        const val tryShortName = "TRY"
        const val usdShortName = "USD"
        const val zarShortName = "ZAR"

        const val audLongName = "Australian Dollar"
        const val bgnLongName = "Bulgarian Lev"
        const val brlLongName = "Brazil Real"
        const val cadLongName = "Canadian Dollar"
        const val chfLongName = "Swiss franc"
        const val cnyLongName = "Chinese Yuan Renminbi"
        const val czkLongName = "Czech koruna"
        const val dkkLongName = "Danish krone"
        const val eurLongName = "European euro"
        const val gbpLongName = "British Pound"
        const val hkdLongName = "Hong Kong dollar"
        const val hrkLongName = "Croatian kuna"
        const val hufLongName = "Hungarian forint"
        const val idrLongName = "Indonesian rupiah"
        const val ilsLongName = "Israeli new shekel"
        const val inrLongName = "Indian rupee"
        const val iskLongName = "Icelandic krona"
        const val jpyLongName = "Japanese yen"
        const val krwLongName = "South Korean won"
        const val mxnLongName = "Mexican peso"
        const val myrLongName = "Malaysian ringgit"
        const val nokLongName = "Norwegian krone"
        const val nzdLongName = "New Zealand dollar"
        const val phpLongName = "Philippine peso"
        const val plnLongName = "Polish zloty"
        const val ronLongName = "Romanian leu"
        const val rubLongName = "Russian ruble"
        const val sekLongName = "Swedish krona"
        const val sgdLongName = "Singapore dollar"
        const val thbLongName = "Thai baht"
        const val tryLongName = "Turkish lira"
        const val usdLongName = "United States dollar"
        const val zarLongName = "South African rand"
    }
}

